[deps]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
NLPModelsModifiers = "e01155f1-5c6f-4375-a9d8-616dd036575f"
QPSReader = "10f199a5-22af-520b-b891-7ce84a7b1bd0"
QuadraticModels = "f468eda6-eac5-11e8-05a5-ff9e497bcd19"
RipQP = "1e40b3f8-35eb-4cd8-8edd-3e515bb9de08"
SparseMatricesCOO = "fa32481b-f100-4b48-8dc8-c62f61b13870"

[compat]
JSON = "0.21"
LinearOperators = "2"
NLPModels = "0.18"
NLPModelsModifiers = "0.5"
QPSReader = "0.2"
QuadraticModels = "0.7.3"
RipQP = "0.3"
SparseMatricesCOO = "0.1"
