[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LinearOperators = "5c8ed15e-5a4c-59e4-a42b-c7e8811fb125"

[compat]
FFTW = "1.4"
JSON = "0.21"
Krylov = "0.7"
LinearOperators = "2.2"
