[deps]
CUTEst = "1b53aba6-35b6-5f92-a507-53c67d53f819"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
CUTEst = "0.12"
JSON = "0.21"
Krylov = "0.8"
NLPModels = "0.18"
Plots = "1"
