[deps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"

[compat]
ADNLPModels = "0.3"
JSON = "0.21"
NLPModelsIpopt = "0.8"
