[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LDLFactorizations = "40e66cde-538c-5869-a4ad-c39174c6795b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixMarket = "4d4711f2-db25-561a-b6b3-d35e7d4047d3"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QPSReader = "10f199a5-22af-520b-b891-7ce84a7b1bd0"
QuadraticModels = "f468eda6-eac5-11e8-05a5-ff9e497bcd19"
RipQP = "1e40b3f8-35eb-4cd8-8edd-3e515bb9de08"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SparseMatricesCOO = "fa32481b-f100-4b48-8dc8-c62f61b13870"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
JSON = "0.21"
LDLFactorizations = "0.8"
MatrixMarket = "0.3"
Plots = "1"
QPSReader = "0.2"
QuadraticModels = "0.7"
RipQP = "0.3"
SparseMatricesCOO = "0.1"
TimerOutputs = "0.5"
