[deps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
JSOSolvers = "10dff2fc-5484-5881-a0e0-c90441020f8a"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
OptimizationProblems = "5049e819-d29b-5fba-b941-0eee7e64c1c6"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
SolverBenchmark = "581a75fa-a23a-52d0-a590-d6201de2218a"

[compat]
ADNLPModels = "0.7"
JSOSolvers = "0.14"
Krylov = "0.10"
OptimizationProblems = "0.7"
Plots = "1"
SolverBenchmark = "0.6"
